### ISSUE TITLE
Q. Writing custom plugin to modify data before sending it to Kafka

### ISSUE THREAD

**Issue by mayankpahwa** [streamsets/datacollector-plugin-api#2]
I was trying out Streamsets to create a pipeline for data ingestion and had a query. I have a directory source to ingest data from a csv file and send it to a kafka producer which I have configured as a destination. In this simple case, if I configure data to be in JSON format, the data would look like
```javascript
{
	"medallion": "F6F7D02179BE915B23EF2DB57836442D",
	"hack": "088879B44B80CC9ED43724776C539370",
	"vendor": "VTS",
	"payment": "CRD",
	"fare": 12.0
}
```
However, before sending data to kafka, I need to convert this JSON to a specific format, something like
```javascript
{
    "fc-app": "testapp",
    "fc-component": ["stremsets"],
    "fc-instance": ["streamsets"],
    "fc-ts": 1523269166918,
    "fc-entity-id": "123456",
    "fc-entity-ns": "test-entity",
    "fc-entity": [{"k" : "medallion", "v" : "F6F7D02179BE915B23EF2DB57836442D"},
                  {"k" : "hack", "v" : "088879B44B80CC9ED43724776C539370"},
                  {"k" : "vendor", "v" : "VTS"},
                  {"k" : "payment", "v" : "CRD"},
                  {"k" : "fare", "v" : 12.0}]
}
```
1. Write to Kafka in the original format and modify the data to the specified format after consuming from Kafka 
2. Write a custom processor plugin to modify the data and publish to Kafka

Could you please suggest which of the above two approaches would be better. I would be happy to know of any other solution to this.

Thanks

**Comment by dimaspivak** [comment]
Please email the SDC user list (sdc-user@streamsets .com) for suggestions of specific use cases; very few eyes follow GitHub issues.
